### ISSUE TITLE
HTML comment in markdown is not supported

### ISSUE THREAD

**Issue by ntnyq** [antfu/vite-plugin-md#102]
It just render the commented content and the comment syntax is ignored.

You can run example and reproduce it.

**Comment by yankeeinlondon** [comment]
please produce a reprodicible example

**Comment by ntnyq** [comment]
> please produce a reprodicible example

[repro](https://github.com/ntnyq/vite-plugin-md-issue-102)

**Comment by yankeeinlondon** [comment]
This should work in `0.19.10`; please let me if you are continuing to have this issue

**Comment by ntnyq** [comment]
The issue still occurs after bumping to `0.19.11`.

Besides, introduced a new issue missing module `@rollup/pluginutils` so that Vite failed to start the dev server and had to install it manually.

**Comment by yankeeinlondon** [comment]
Sorry that the issue still presents. I'll have another look at that and add a test for the specific use case.

WRT to `@rollup/pluginutils` ... it's listed as a peer dependency of `vite-plugin-md` and at this point it would appear it needs to be as that library has some CJS-only deps that play poorly with Vite3.

**Comment by yankeeinlondon** [comment]
if you don't know ... you can add an entry to `.npmrc` to make all peer dependencies get automatically installed (like they always used to be). I'd suggest that you do this if you don't like the manual install process (which of course you can still do if you want to even with this setting in place).

**Comment by yankeeinlondon** [comment]
Ok, it appears this is the default behavior of the `gray-matter` package so I'm presuming this was never working in an earlier version.

**Comment by yankeeinlondon** [comment]
update: on further testing it is NOT gray-matter but either `happy-dom` or my wrapper around it. I'll get this fixed today.

**Comment by yankeeinlondon** [comment]
ok, really should be fixed this time in `0.20.0`; please re-open if you feel it's not working as expected.
