### ISSUE TITLE
string `process.env.NODE_ENV` in codeblock  is generated into its value

### ISSUE THREAD

**Issue by yzqdev** [antfu/vite-plugin-md#103]
when I write `process.env.NODE_ENV` in markdown codeblock. It will gen the result rather than origin string `process.env.NODE_ENV`

![image](https://user-images.githubusercontent.com/20037151/175807281-62654f69-56d1-4bfb-a1cd-5fd2beeca99a.png)

here is my minial repo [stackblitz](https://stackblitz.com/edit/vitejs-vite-wxbcn8?file=package.json,vite.config.js,src%2Fcomponents%2FHelloWorld.md,src%2FApp.vue&terminal=dev)

**Comment by yankeeinlondon** [comment]
i believe this is now fixed in `0.19.10`; give it a try and let me know

**Comment by yzqdev** [comment]
Great, thank you. It seems only `process.env.NODE_ENV` has this issue, the other environment varibles not, so close it
