### ISSUE TITLE
just install it seems like it's not enough

### ISSUE THREAD

**Issue by nolandcheng** [antfu/vite-plugin-md#104]
Excuse me. I was update `vite-plugin-md` to `0.18.1` from `0.13.1`, but i need to install `happy-dom`、`markdown-it` `prismjs` to run successfully。
Is this the right process or my Installation mode is wrong？thanks

**Comment by Mert75** [comment]
Same issue with me with `happy-dom` package on a fresh installation

**Comment by AlanMorel** [comment]
I can confirm this issue is happening to me as well

**Comment by yankeeinlondon** [comment]
a bit odd but I wonder if it's due to the recent change in **npm**'s behavior WRT to peer dependencies.

**Comment by yankeeinlondon** [comment]
You should be able to upgrade to `0.19.10` and have everything work. The one thing which I haven't done yet is expose the builder apis so you'll need to import them manually if you want to (the "example app" shows this).

**Comment by yankeeinlondon** [comment]
I suggest that everyone install `0.20.0` and I believe all will work well. Please remember that package managers have changed their default behavior toward "peer dependencies" (in that they no longer automatically install them in the background) but you can revert to the old behavior by adding an `.npmrc` file to the root of your project and adding:

```toml
auto-install-peers=true
```
