### ISSUE TITLE
Support Vite 3

### ISSUE THREAD

**Issue by jeremeevans** [antfu/vite-plugin-md#105]
### Describe the bug

This package can currently not be installed when using Vite 3, which is out now.

### Reproduction

Use Vite 3, attempt to install this package. It fails due to peer dependencies.

### System Info

```Shell
All
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yankeeinlondon** [comment]
I have a feature branch which is Vite 3 ready

**Comment by holtwick** [comment]
+1 

<img width="401" alt="grafik" src="https://user-images.githubusercontent.com/49557/180479585-92c064d4-f0a9-4bbc-a3c7-8d6df960ed56.png">

**Comment by yankeeinlondon** [comment]
the branch aforementioned has been released now and Vite 3 should be fully supported
