### ISSUE TITLE
Support dynamic import of markdown

### ISSUE THREAD

**Issue by ZCY1715** [antfu/vite-plugin-md#107]
### Clear and concise description of the problem

I try to match different files according to certain rules by dynamically importing markdown files, but this method can run successfully in the development mode and report errors after packaging

![image](https://user-images.githubusercontent.com/75206433/179914046-43125d3f-21dc-4924-b77f-e1cea336f3a0.png)
![image](https://user-images.githubusercontent.com/75206433/179914211-b0788df3-bd4e-49e0-a15d-847cce9553e9.png)

### Suggested solution

I don't know how to solve this problem

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ZCY1715** [comment]
Sorry, I found a solution

**Comment by Kadeluxe** [comment]
It would be helpful what was the solution, I also have that problem.
