### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by flingyp** [antfu/vite-plugin-md#109]
### Describe the bug

use pnpm to install all dependencies, but execute pnpm example:dev to report an error

### Reproduction

TypeError: (0 , import_vite_plugin_md.meta) is not a function

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 2.30 GB / 7.88 GB
  Binaries:
    Node: 16.13.0 - G:\ItSoftware\nodejs\node.EXE
    Yarn: 1.22.17 - F:\globalNpm\node_gobal\yarn.CMD
    npm: 8.1.0 - G:\ItSoftware\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yankeeinlondon** [comment]
which version of the plugin did you use?

**Comment by flingyp** [comment]
I use the latest code of the repository. The version of vite is ^3.0.2 but still not work.

**Comment by yankeeinlondon** [comment]
the latest release -- `0.19.10` -- works with Vite 3; the example app also works and shows how to manually import the "builder apis" (code, meta, link) if you're using them.
