### ISSUE TITLE
Support Vue 2

### ISSUE THREAD

**Issue by fengyuanchen** [antfu/vite-plugin-md#110]
### Clear and concise description of the problem

The `@vitejs/plugin-vue` peer dependency is not compatible with Vue 2.

### Suggested solution

Remove the `@vitejs/plugin-vue` package from peer dependencies, so that users can install `@vitejs/plugin-vue2` for Vue 2.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yankeeinlondon** [comment]
should be done in `0.20.1`; sorry for the inconvenience
