### ISSUE TITLE
Is the code theme of vitepress open? I want to use the highlight style of vitepress, what should I do?

### ISSUE THREAD

**Issue by social-uni** [antfu/vite-plugin-md#115]
Is the code theme of vitepress open? I want to use the highlight style of vitepress, what should I do?

thanks

**Comment by antfu** [comment]
This project is not related to VitePress, please refer to it's docs or source code.

**Comment by social-uni** [comment]
> 

![image](https://user-images.githubusercontent.com/14007972/186634987-b9900a11-18b6-4383-aadd-2f02b9218740.png)

Hello, I am here for help, I am using the vite-plugin-md project, and I want to use the vitepress theme in this project, and I know that you, as the initiator of this project, have a certain relationship with vitepress Yes, that's why I came here for help

If you want to use a code style similar to vitepress in the vite-plugin-md project, what would you do, would you use markdown-it to implement it, is there a better way,

I'm here for help, thanks, sorry

**Comment by social-uni** [comment]
> This project is not related to VitePress, please refer to it's docs or source code.

https://github.com/vuejs/vitepress/issues/1237

I have submitted a related issue in issues of vitepress, thank you
