### ISSUE TITLE
How to achieve the same markdown rendering effect as github？

### ISSUE THREAD

**Issue by social-uni** [antfu/vite-plugin-md#117]
I want my page to have the same effect of rendering markdown as github, do you know how to do it?

I now use vite-plugin-md + github-markdown-css

My effect is as follows

![256f2ca1f5d8b7cba1cce44a3d2e5b4](https://user-images.githubusercontent.com/14007972/186938410-4620d266-3a94-44a8-9004-b28383bdf453.jpg)

The following is the rendering effect of github
![cfbe65ae59d5dc926caf283d4ad785e](https://user-images.githubusercontent.com/14007972/186938531-5aae1607-b0d2-4b04-b039-b595b0fb20e0.jpg)

Compared with the rendering effect of github, my rendering effect is missing the link, I want to add him, what should I do? Need to write a markdown-it plugin, or do you know any other better way

thank you

**Comment by social-uni** [comment]
markdown-it-github-headings solved my problem

**Comment by HeiShuXianSheng** [comment]
@social-uni 可以看看你的样式引入吗，我渲染的md没有样式
