### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@rollup/pluginutils'

### ISSUE THREAD

**Issue by mzenz** [antfu/vite-plugin-md#121]
### Describe the bug

Creating a basic starter Vite + Vue + TS project via `yarn create vite@latest` fails to start dev server after installing `vite-plugin-md`.

Repro steps:

- `yarn create vite@latest` -> choose Vue + Typescript
- `yarn install vite-plugin-md`.
- Perform [install steps](https://github.com/antfu/vite-plugin-md#installing-this-plugin).
- Start dev server via `yarn dev`.

### Reproduction

https://github.com/mzenz/vite-plugin-md-bug

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 32.39 MB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Hextar** [comment]
I'm also trying to updated my project to use `vite 3` and encountered that issue
![image](https://user-images.githubusercontent.com/8740725/191726786-ad40ebd1-629f-4fbe-aed8-9335191c2595.png)

**Comment by ntnyq** [comment]
Done it manually.

**Comment by holtwick** [comment]
I see the same problem. I installed the dependencies, but the references in vite-plugin-md are outdated. New major versions of rollup and happy-dom are available. It would be great, if these dependencies could be updated in this project as well. Thanks.

```
WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-md 0.20.4
  ├── ✕ unmet peer rollup@^2.77.0: found 3.2.3
  └─┬ @yankeeinlondon/builder-api 0.4.1
    └─┬ @yankeeinlondon/happy-wrapper 2.6.0
      └── ✕ unmet peer happy-dom@^6.0.4: found 7.5.13
```

**Comment by nolandcheng** [comment]
I had a similar issue. And I need to fix it by installing `happy-dom`, I think the reason may be because I updated vite3 in my project

**Comment by yankeeinlondon** [comment]
I believe everything after [Release v0.22.0](https://github.com/antfu/vite-plugin-md/releases/tag/v0.22.0) should work fine now. Please re-open if that is not the case.
