### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Hoopex** [antfu/vite-plugin-md#123]
### Describe the bug

I'm getting this issue last 2 days.

`[ERR_REQUIRE_ESM]: require() of ES Module \node_modules\brilliant-errors\node_modules\callsites\index.js from \node_modules\brilliant-errors\dist\index.cjs not supported.`

### Reproduction

Vue

### System Info

```Shell
'envinfo' is not recognized as an internal or external command,
operable program or batch file.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Discreater** [comment]
This may be  caused by `brilliant-errors`. See the [related issue ](https://github.com/inocan-group/brilliant-errors/issues/1).

**Comment by Hoopex** [comment]
@Discreater Yeah I know, But this plugin not gonna work since that package has that issue
By the way, I fixed that temp by installing v0.60 in my project, Bu still not a good way.

**Comment by dxlliv** [comment]
Don't ask me why or how, but it works if you put in the package.json

```js
"resolutions": {
  "brilliant-errors": "0.6.0"
}

**Comment by yankeeinlondon** [comment]
I believe everything after [Release v0.22.0](https://github.com/antfu/vite-plugin-md/releases/tag/v0.22.0) should work fine now. Please re-open if that is not the case.

**Comment by lyh543** [comment]
@yankeeinlondon Thank you for your work! It seems that `v0.22.0` is not published to npm, is there any mistakes?
