### ISSUE TITLE
It doesn't seem to support vue2

### ISSUE THREAD

**Issue by hcw2175** [antfu/vite-plugin-md#13]
Hi，I installed this plug-in on the VUE2 version, but it doesn't seem to support VUE2. 

The following exceptions occurred during installation:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: iotp-web@4.0.0
npm ERR! Found: vue@2.6.12
npm ERR! node_modules/vue
npm ERR!   vue@"^2.6.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.0.7" from @vue/compiler-sfc@3.0.7
npm ERR! node_modules/@vue/compiler-sfc
npm ERR!   peer @vue/compiler-sfc@"^3.0.5" from vite-plugin-md@0.6.2
npm ERR!   node_modules/vite-plugin-md
npm ERR!     dev vite-plugin-md@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

npm ERR! A complete log of this run can be found in:
```

Can't I use it on vue2?

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by hcw2175** [comment]
> Can you share a minimal reproduction? Thanks.

I am using this vue2 + vite2 template：[vite-vue2-windicss-starter](https://github.com/lstoeferle/vite-vue2-windicss-starter)

You can download it and execute the command to install dependencies： `npm install`.

Then install this plugin you can see the error:

![image](https://user-images.githubusercontent.com/8132286/112121875-afa76480-8bfa-11eb-9157-0a944aea24a6.png)

**Comment by antfu** [comment]
Can you try with `--force`? npm@7 sometimes could be troublesome

**Comment by hcw2175** [comment]
> Can you try with `--force`? npm@7 sometimes could be troublesome

It's worked !!!   Thank you ~

```
// install plugin
npm i vite-plugin-md -D --force

// vite.config.js
import {createVuePlugin} from 'vite-plugin-vue2';
export default  {
  plugins: [
    createVuePlugin({
      include: [/\.vue$/, /\.md$/]
    })
  ]
}
```

**Comment by Codermar** [comment]
I am not able to make this work with Vue 2. I've used vite-vue2-windicss-starter as well. Then added vite-plugin-md. I get:

```Uncaught ReferenceError: defineExpose is not defined
    at README.md:6```

My vite.config.js
```import path from "path";
import { defineConfig } from "vite";
import { createVuePlugin } from "vite-plugin-vue2";
import ViteComponents from "vite-plugin-components";
import WindiCSS from "vite-plugin-windicss";
import ViteIcons, { ViteIconsResolver } from "vite-plugin-icons";
import Markdown from "vite-plugin-md";

const config = defineConfig({
  resolve: {
    alias: {
      "@": `${path.resolve(__dirname, "src")}`,
    },
    dedupe: ["vue-demi"],
  },

  build: {
    minify: true,
  },

  plugins: [
    createVuePlugin({
      include: [/\.vue$/, /\.md$/],
    }),
    Markdown(),
    ViteComponents({
      customComponentResolvers: [
        ViteIconsResolver({
          componentPrefix: "",
        }),
      ],
    }),
    ViteIcons({
      defaultStyle: "",
    }),
    WindiCSS(),
  ],

  server: {
    port: 8077,
  },
});

export default config;
```

**Comment by antfu** [comment]
A temporary workaround:

```ts
Markdown({
  exposeFrontmatter: false
})
```

**Comment by antfu** [comment]
@Codermar should be fixed in v0.11.0

**Comment by Codermar** [comment]
> @Codermar should be fixed in v0.11.0

Thank you!

**Comment by Codermar** [comment]
@antfu Quick question. Is is possible to via option make it return the markdown content and not the sfc? So I can dynamically do something like ```const { body } = await import(`./doc-content${page.file}`);```
Let me know. Thanks

**Comment by antfu** [comment]
Use `?raw` to get the raw markdown. And you need to use glob to fetch them, dynamic constructed import function will not work for bundlers. https://vitejs.dev/guide/features.html#glob-import
