### ISSUE TITLE
Add character references for curly brackets

### ISSUE THREAD

**Issue by Ahacad** [antfu/vite-plugin-md#14]
See slidevjs/slidev/issues/95.

The double curly brackets are in collision with the vue syntax, maybe should change all curly brackets to character references after `markdown-it` rendering.

**Comment by woldtwerk** [comment]
as a workaround  you can do this:
```
Markdown({
  transforms: {
    after: (code: string, id: string) => 
      code.replace(/<code>/g, '<code v-pre>')
  }
}),
```

It add a v-pre to all code tag, which skips  parsing of that element. See https://v3.vuejs.org/api/directives.html#v-pre
