### ISSUE TITLE
ReferenceError: defineExpose is not defined in index.md:6

### ISSUE THREAD

**Issue by pbastowski** [antfu/vite-plugin-md#19]
I'm getting the error 
`ReferenceError: defineExpose is not defined in index.md:6` 
after upgrading to 0.8.0. There was no error with 0.6.7. 

I have confirmed that the error starts with 0.7.0 and continues with 0.8.0.

Here is the generated index.md

```html
<template><div class="markdown-body"><h1>This is the app home page</h1>
<router-view />
</div></template>
<script setup>
const frontmatter = {}
defineExpose({ frontmatter })
</script>
```

and here the original `index.md`

```html
# This is the app home page

<router-view />
```

I am using `vite-plugin-md` together with `vite-plugin-pages` and `vite-plugin-components`.

However, as I stated earlier, the problem disappears when I revert `vite-plugin-md` to 0.6.7.

**Comment by antfu** [comment]
?What's your vue version

**Comment by pbastowski** [comment]
Sorry for the late reply, the vue and compiler versions are below.

"vue": "3.0.11",
"@vue/compiler-sfc": "3.0.11",

**Comment by antfu** [comment]
Consider upgrade to the latest version, the `<script setup>` syntax has changed a bit

**Comment by Codermar** [comment]
I have the same problem. I've started with the template vite-vue2-windicss-starter then added vite-plugin-md, I also updated all dependencies still have the problem with "vite-plugin-md": "^0.10.0", when I revert to 0.6.7 the issue goes away
