### ISSUE TITLE
Parsing frontmatter yaml

### ISSUE THREAD

**Issue by DeFUCC** [antfu/vite-plugin-md#2]
Hey! Thank you for your great work at creating this vite ecosystem.

I enjoy adapting vioe and component auto imports into my current vite projects. I makes me think of moving my Grav PHP CMS website to vite too. It's a flat file CMS and I already have the .md files to use. But I have so much details for each page in the frontmatter YAML section of every file... Can you advice a strategy of parsing this info and using it as data for rendering those .md pages?

**Comment by antfu** [comment]
Yeah, this is definitely a feature to have, I will think about it a bit and implement it later. PR welcome as well.
