### ISSUE TITLE
Index page listing all md files

### ISSUE THREAD

**Issue by sistematico** [antfu/vite-plugin-md#21]
It's possible to create a index page listing all md files? Like a "posts" index?

**Comment by antfu** [comment]
Here is an example https://github.com/antfu/antfu.me/blob/2977b4210a8fb44bb8398f6a0d8255b55abfeb2f/vite.config.ts#L54-L63

**Comment by sistematico** [comment]
This with conflict with default Vitesse vite.config.js right?

![code](https://user-images.githubusercontent.com/97509/127548627-1016211f-6898-47c3-9386-945973d36c00.png)

**Comment by sistematico** [comment]
nvm, i think i got it! Thank you very, very much! Awesome job.
