### ISSUE TITLE
Provide page id to the markdown-it env

### ISSUE THREAD

**Issue by Apostolique** [antfu/vite-plugin-md#22]
I like to rewrite links based on the page id. It would be nice if it was injected in the markdown-it env:

https://github.com/antfu/vite-plugin-md/blob/ca1df47f4c7e9aa2c47e714130e704fa551e0f0c/src/markdown.ts#L61

For example:

```js
let html = markdown.render(md, { id })
```

I can do a PR if this is wanted.

**Comment by antfu** [comment]
that's a good call, pr welcome!
