### ISSUE TITLE
Access frontmatter object from container component

### ISSUE THREAD

**Issue by rderimay** [antfu/vite-plugin-md#24]
This is not a bug.
I would like to access the frontmatter object from the containing component without using the wrapperComponent option because I have multiple routes and need to have different wrapping components depending on the route.
Is there a way to do this?

Many thanks!

**Comment by antfu** [comment]
it's already available as `frontmatter` https://github.com/antfu/vite-plugin-md#frontmatter

**Comment by rderimay** [comment]
Thanks for helping out. I see that the rendered MD component has the frontmatter object but it is not "bubbling up" to the Blog component for example and I can not find a way to access it from the Blog component :-(

I could use the wrapperComponent option with a component that would emit the frontmatter object but their should be a nicer way. Need to become better in Vue 3...

![image](https://user-images.githubusercontent.com/12871929/129644787-e5d2fca2-5fed-4768-93c6-07aea843dcad.png)
