### ISSUE TITLE
It appears that markdownItOptions does not support the highlight function

### ISSUE THREAD

**Issue by jekip** [antfu/vite-plugin-md#26]
If you could take a look and fix some

**Comment by jekip** [comment]
![QQ截图20210904221045](https://user-images.githubusercontent.com/19426584/132097378-9c4a11c4-9830-498e-9207-d8c65b390260.png)

**Comment by yankeeinlondon** [comment]
@jekip I don't believe that is part of the core API is it? [API Docs](https://markdown-it.github.io/markdown-it/). I think what you're looking for is the result of using a plugin to Markdown-IT. Maybe Prism or Highlighter.js?

**Comment by jekip** [comment]
> @jekip I don't believe that is part of the core API is it? [API Docs](https://markdown-it.github.io/markdown-it/). I think what you're looking for is the result of using a plugin to Markdown-IT. Maybe Prism or Highlighter.js?

you're right Finally, the solution was combined with Highlighter
