### ISSUE TITLE
markdown-it-shiki error in vite build

### ISSUE THREAD

**Issue by sadeghbarati** [antfu/vite-plugin-md#31]
works fine in Vite dev

`"vite-plugin-md": "^0.11.4"`

```js
import shiki from 'markdown-it-shiki'

...

Markdown({
      wrapperClasses: markdownWrapperClasses,
      headEnabled: true,
      markdownItSetup(md) {

        md.use(shiki)
        md.use(LinkAttributes, {
          pattern: /^https?:\/\//,
          attrs: {
            target: '_blank',
            rel: 'noopener',
          },
        })
    },
}),

...

```

---

Vite build **Promise { < pending > }**:

[vite-plugin-md] Shiki.getHighlighter() never gets resolved
file: F:/Test/vite-vitessg/src/pages/about.md
Error: Shiki.getHighlighter() never gets resolved
    at Object.MarkdownItShiki.markdownit.options.highlight (F:\Test\vite-vitessg\node_modules\markdown-it-shiki\dist\index.js:73:17)
    at Object.default_rules.fence (F:\Test\vite-vitessg\node_modules\markdown-it\lib\renderer.js:53:27)
    at Renderer.render (F:\Test\vite-vitessg\node_modules\markdown-it\lib\renderer.js:332:38)
    at MarkdownIt.render (F:\Test\vite-vitessg\node_modules\markdown-it\lib\index.js:544:24)
    at F:\Test\vite-vitessg\node_modules\vite-plugin-md\dist\index.js:106:25
    at Object.transform (F:\Test\vite-vitessg\node_modules\vite-plugin-md\dist\index.js:228:16)
    at F:\Test\vite-vitessg\node_modules\rollup\dist\shared\rollup.js:22620:25 {
  id: 'F:/Test/vite-vitessg/src/pages/about.md',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-md',
  watchFiles: [
    'F:/Test/vite-vitessg/index.html',
    'vite/modulepreload-polyfill',
    'F:/Test/vite-vitessg/src/main.js',
    '/@vite-plugin-pages/generated-pages',
    '/@vite-plugin-vue-layouts/generated-layouts',
    'F:/Test/vite-vitessg/src/modules/nprogress.js',
    'F:/Test/vite-vitessg/src/modules/pinia.js',
    'F:/Test/vite-vitessg/node_modules/vite-ssg/dist/index.mjs',
    'F:/Test/vite-vitessg/src/App.vue',
    'F:/Test/vite-vitessg/src/styles/main.css',
    '/@windicss/devtools',
    '/@windicss/windi-base.css',
    '/@windicss/windi-components.css',
    '/@windicss/windi-utilities.css',
    'F:/Test/vite-vitessg/src/pages/index.vue',
    'F:/Test/vite-vitessg/src/pages/about.md',
    'F:/Test/vite-vitessg/src/pages/[...all].vue',
    'vite/preload-helper',
    'F:/Test/vite-vitessg/src/layouts/default.vue',
    'F:/Test/vite-vitessg/src/layouts/404.vue',
    'F:/Test/vite-vitessg/node_modules/nprogress/nprogress.js',
    'F:/Test/vite-vitessg/node_modules/pinia/dist/pinia.esm-browser.js',
    'F:/Test/vite-vitessg/node_modules/@vueuse/head/dist/index.mjs',
    'F:/Test/vite-vitessg/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    'plugin-vue:export-helper'
  ]
}

**Comment by yankeeinlondon** [comment]
This appears to not be related to this plugin but rather your integration with shiki. Can we close this?
