### ISSUE TITLE
Feature request: get access to frontmatter vars on children routes

### ISSUE THREAD

**Issue by bux** [antfu/vite-plugin-md#35]
When using vite-plugin-md in combination with vite-plugin-pages and similar it would be very convenient to be able to access the frontmatter values of child routes.

Use case would be to automatically render a subnavigation that displays e.g. the title of a child page.

**Comment by mythz** [comment]
Is there an inconvenient way to access frontmatter from routes? I'm also using [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) and can't see a way to access the associated frontmatter or even the Markdown component itself from the generated route.

**Comment by mythz** [comment]
Ok was browsing [antfu.me/vite.config.ts](https://github.com/antfu/antfu.me/blob/main/vite.config.ts) for a more advanced configuration example and was able to find how it's done:

```ts
Pages({
  extensions: ['vue', 'md'],
  pagesDir: 'pages',
  extendRoute(route) {
    const path = resolve(__dirname, route.component.slice(1))

    if (!path.includes('projects.md')) {
      const md = fs.readFileSync(path, 'utf-8')
      const { data } = matter(md)
      route.meta = Object.assign(route.meta || {}, { frontmatter: data })
    }

    return route
  },
}),
``

But also agree, I'd expect for attaching frontmatter to the routes meta to be a popular feature request as it's required for being able to generate a list of markdown page links (e.g. blog posts) from routes.

**Comment by mathieutu** [comment]
Hi, maybe https://github.com/antfu/vite-plugin-md/pull/42 could help you?

**Comment by yankeeinlondon** [comment]
I have added the ability to plugin "builders" and I wonder if maybe the [Meta Builder](/docs/MetaBuilder.md) might help you solve your issue?

**Comment by yankeeinlondon** [comment]
I'm closing this for now ... please add a clear example if you think it should be re-openned (after looking at the suggested `meta()` builder suggested above.
