### ISSUE TITLE
Not an issue, but question: How to import all markdown files and render it in v-for to components?

### ISSUE THREAD

**Issue by sdoerger** [antfu/vite-plugin-md#39]
I would like to import all markdwon files at once and render them in a v-for-loop as components, like:

```html
<template lang="pug">

template(v-for="version in allVersions")
  component(:is="version") 

</template>

<script lang="ts" setup>
  // VUE
  import { computed } from 'vue'
    // CONTENT
    const allVersions = import.meta.globEager('/src/content/pages/about/*.md');

      const component = computed(() => {
        if (allVersions) {
          const versionComponents = {};
          for (const version in allVersions) {
            if (Object.prototype.hasOwnProperty.call(allVersions, version)) {
              const element = allVersions[version];
              // const newVersionKey = String(version).replace(/\/src\/content\/pages\/about\/.*\.md/, '')
              const newVersionKey = String(version).replace('/src/content/pages/about/', '').replace('.md', '');
              // const newVersionKey = String(version).replace('/src/content/pages/about/', '')
              console.log(newVersionKey);
              versionComponents[newVersionKey] = element;
            }
          }
          return versionComponents;
        } else {
          return false;
        }
      }]]
</script>
```

So I get the files but I can not render them ... 
Is there a way to make it work.

Thanks in advance

**Comment by mathieutu** [comment]
Hi @sdoerger , actually you're not far from something working.

I think you forgot to extract the default export in your object.

I don't really understand why you're doing all this computation on your array. The code I would write myself would be: 
```js
    const allVersions = Object.values(import.meta.globEager('/src/content/pages/about/*.md'))
	  .map(({ default: component }) => component)
```
and so you have an array of version components that you can iterate and pass to `component :is`

👋 
Mathieu

**Comment by sdoerger** [comment]
Yeeees. Thank you so much @mathieutu. Can't tell how happy that makes me.
Yes, that is much more elegant. I rarely use actually .map.
So my new year resolution: More .map :)

So, here I map over just the object values of the import and from there I "pass" the key-value-pair default: component and return just the value of it, which gives much a clean array of components?

Thank in advance

**Comment by mathieutu** [comment]
Glad to see it helps.

An export can be named, or default : 
`import { named1, named2 }, defaultExport from 'foo`

When you import all the module, you will have an object with 
```js
{ 
	default: ...,	// default export
	named1: ..., 	// named export
	named2: ...,	// named export
}
```

Here you just want the default export, so you can map over the modules, to get only it.

And by the way I can only recommend you to ban for loop from your code, and use the dedicated utilities like map, filter, reduce etc. You code will only be better and more readable! 😉
