### ISSUE TITLE
Load MD files dinamically instead of creating a especific component?

### ISSUE THREAD

**Issue by ctwhome** [antfu/vite-plugin-md#45]
Hallo @antfu thank you for the efforts you are making to make the Vue world shine!

I have `vite-plugin-md` working with Nuxt 3 perfectly, but I wonder if it is possible to load a markdown file dynamically, for example from the router params. Something like `<markdown :content="$route.param.page">` or similar

```js
<script setup>
  import PostComponent from '~/content/post.md'   // Load dynamically?
</script>

<template>
  <div class="container mx-auto pt-4">
    <h1> {{ $t('about') }}</h1>

    <PostComponent class="prose"/>

   <!-- Something like this: -->
   <markdown :content="$route.params.page">
  </div>
</template>
```

**Comment by ctwhome** [comment]
So this loads the modules but I still wouldn't know how to use them in the Vue template?

```
const posts = Object.values(import.meta.globEager('../content/blog/*.md'))
```

**Comment by ctwhome** [comment]
And apparently in not possible to import files dinamically, let's say from a router param according to vite documentation for import.meta.globEager.

If I understand correctly there is no way to make it work dinamically?

**Comment by antfu** [comment]
That's not in the scope of this project, if you need dynamic, you can directly import `markdown-it` in the runtime.

**Comment by antfu** [comment]
Or if you are just want to build a blog, here is mine using this plugin, https://github.com/antfu/antfu.me, for you to reference.

**Comment by ctwhome** [comment]
yes, the idea is to have a blog like yours, but running with Nuxt. I tried to use vite-pages but I couldn't get it to work
