### ISSUE TITLE
`wrapperClasses` no longer works since v0.12

### ISSUE THREAD

**Issue by antfu** [antfu/vite-plugin-md#57]
https://github.com/antfu/antfu.me/blob/4da2324c0ca7f52ca9247b0ba5cce6bb9d589437/vite.config.ts#L93

If you upgrade to v0.12 you will see the class is not injected. 

/cc @yankeeinlondon incase you know a quite solution before I look into it, thanks!

**Comment by yankeeinlondon** [comment]
Just back from skiing. I'll get a test in for that and get it fixed.

**Comment by yankeeinlondon** [comment]
So it I believe `wrapperClass` by itself does work but when you use it in conjunction with `wrapperComponent` things go awry. I'm not 100% sure I understand expected behavior here but I'll look at v0.11 to see if I can figure it out.

**Comment by yankeeinlondon** [comment]
Not sure what review process you'd typically do for fixes like this but have raise a PR for now
