### ISSUE TITLE
Issue #13 is back after 0.12.0 upgrade

### ISSUE THREAD

**Issue by Codermar** [antfu/vite-plugin-md#58]
[issue 13](https://github.com/antfu/vite-plugin-md/issues/13) is back after I upgraded "vite-plugin-md": "0.12.0" or "vite-plugin-md": "0.12.1"

The workaround of the original issue makes it work as it did before: in vite.config
```
    Markdown({
    ...
   exposeFrontmatter: false, 
})
```

> @Codermar should be fixed in v0.11.0

Thank you! It's all good both with workaround and now with new release v0.11.0

_Originally posted by @Codermar in https://github.com/antfu/vite-plugin-md/issues/13#issuecomment-899932940_

**Comment by yankeeinlondon** [comment]
@Codermar I'm going to create a unit test to try and ensure that the functionality you're looking for is captured as a test and therefore not regressed going forward. I can dig through this history but if you had time for a quick bullet pointed description that might help.

**Comment by yankeeinlondon** [comment]
I have run tests on Vue2 and Vue3 and with `exposeFrontmatter` set to true and false and the behavior that v0.12.x is providing seems to be consistent and correct unless there is an undocumented feature hiding out somewhere.

**Comment by yankeeinlondon** [comment]
You can see these tests in PR #60
