### ISSUE TITLE
Using with vue 2 and vite-plugin-vue2

### ISSUE THREAD

**Issue by naknode** [antfu/vite-plugin-md#63]
Trying to import vue 2 component with a markdown file...

```
CHANGELOG.md:4830 Uncaught ReferenceError: defineExpose is not defined
    at CHANGELOG.md:4830:1
(anonymous) @ CHANGELOG.md:4830
```

vite: 2.9.1
vue: 2.6.14
vue-template-compiler: 2.6.14
vite-plugin-md: 0.12.4

**Comment by yankeeinlondon** [comment]
Thanks for reporting this ... i've been trying to build a full set of tests so we don't have regressions going forward but while I have some synthetic tests for Vue2 we don't have tests that actually load Vue2. In any event, I just released a PR yesterday that @antfu has merged but not released yet to **npm** ... I'd expect this soon as `v0.12.5` and it should correct this error.

**Comment by yankeeinlondon** [comment]
@naknode there were some changes made that might help with the problem you were having. Upgrade to the latest version and re-open this issue if you're still having it but be sure to create a minimally reproducible example with https://vite.new/vue
