### ISSUE TITLE
How to enable export frontmatter as named exports?

### ISSUE THREAD

**Issue by imShara** [antfu/vite-plugin-md#65]
I'm using [vite-plugin-md](https://github.com/antfu/vite-plugin-md) with Vite 2.9.3
I have found that this [should work](https://github.com/antfu/vite-plugin-md/pull/42) win default parameters, but it not works.

```markdown
---
title: Hey
---

# Hello World
```

```vue
<script setup>
	import MyComp, { title } from './my-comp.md'
</script>
<template>
	<h1>{{ title }}</h1>
	<MyComp />
</template>
```

```
import not found: title
```

I tried to rewrite default parameters to expose frontmatter, but it not helps

```js
      markdown({
        exposeFrontmatter: true
      }),
```

**Comment by imShara** [comment]
Tried to manually export vars with and without `setup` script, but nothing works.
```
---
title: "About yay"
---

<script setup>
  export const test = "YAY";
</script>

about
```

```
[plugin:vite:vue] Tags with side effect (<script> and <style>) are ignored in client component templates.
```

Tried to manually export vars
```
---
title: "About yay"
---

<script>
  export const test = "YAY";
</script>

about
```

```
[plugin:vite:vue] Tags with side effect (<script> and <style>) are ignored in client component templates.
```

**Comment by mathieutu** [comment]
Hi @imShara please don't send emails in addition to opening issue.

It worked at the time of the PR, can't say for now, sorry. Maybe there was a regression.

**Comment by mathieutu** [comment]
It's weird as it seems to work in [tests](https://github.com/antfu/vite-plugin-md/blob/main/test/__snapshots__/exposeFrontmatter.test.ts.snap)

**Comment by imShara** [comment]
Is `defineExpose` works only for parent components?

> Components using <script setup> are closed by default - i.e. the public instance of the component, which is retrieved via template refs or $parent chains, will not expose any of the bindings declared inside <script setup>.

But this is not like `export` and you can't import variable like this:

**`component.md`**
```md
---
test: "Yay!"
---

I am component
```


**`check.vue`**
```vue
<script setup>
import {test} from './component.md'
console.log(test)
</script>
```

**Comment by yankeeinlondon** [comment]
@mathieutu snapshot tests tell part but not all of the story ... I created that test as I was involved in a major refactor to bring in more pipelining functionality and wanted to articulate _existing_ features as best I could. Looking at the snapshot I would say that both Vue2 and Vue3 outputs _look_ right but I at least in Typescript, i'm not finding any way to avoid errors when trying to import even the default export from a markdown file. 

Here's a humble beginning of a test I was writing but stopped when I realized I don't know what is needed to communicate that a `*.md` file is a valid import.

![image](https://user-images.githubusercontent.com/980757/164558912-6ce47002-0fa1-4e40-9cdb-961683e9176f.png)

**Comment by yankeeinlondon** [comment]
Ok, i've figured that out ... just needed the proper shim in my test directory. Let me create a more detailed test to see where this is. I'm in a feature directory but if the test passes here I'll share the results here and am hoping to close this feature out in the next day or two.

**Comment by yankeeinlondon** [comment]
first question ... can you import `frontmatter` symbol?

```ts
import {frontmatter} from './component.md'
console.log(frontmatter.test
```

**Comment by imShara** [comment]
> first question ... can you import `frontmatter` symbol?

Nope

```
Uncaught SyntaxError: import not found: frontmatter
```

**Comment by yankeeinlondon** [comment]
Ok, i believe there's a very good chance that `v0.13.0` which I contributed to has fixed this now

**Comment by imShara** [comment]
Cool, It works again, thanks!
