### ISSUE TITLE
Set route with frontmatter variable?

### ISSUE THREAD

**Issue by coderzhaoziwei** [antfu/vite-plugin-md#72]
```html
<route lang="yaml">
name: RouteName
path: /route/path
title: Title
meta:
  requiresAuth: true
</route>
```

Route setting is ok as above, when using `vite-plugin-pages`.

So, how about using frontmatter variable to set route?

```markdown
---
name: RouteName
path: /route/path
title: Title
meta:
  requiresAuth: true
---
```

**Comment by yankeeinlondon** [comment]
I believe this functionality is _intended_ to be present if you use the [`meta()` builder](https://github.com/antfu/vite-plugin-md/blob/main/docs/MetaBuilder.md) in your configuration. Have you tried this? The idea is that if you use this _builder_ you will be able to state which frontmatter properties should be treated as "route properties" and these properties will be set in the router's configuration like your example of `requiresAuth`.

I believe out of the box the only property which is set to be auto-associated with the route is `layout` so you can state the layout you want to use but you can configure any properties to be included in `vite.config.ts`:

```ts
{
  // ...
  plugins: [
    Markdown({
      builders: [  meta( { routeProps: ['requiresAuth'] } )  ],
    })
  ]
}

```

**Comment by yankeeinlondon** [comment]
Looking at the test suite, I think this is under-represented (aka, there aren't any tests yet) so I'll add some now to a PR i'm working on as I think this feature is really important.

**Comment by yankeeinlondon** [comment]
I can confirm that testing was needed. The router metadata was being configured but not added to the document at the end of the transformation pipeline. I have fixed that in my current PR and have tests that should give this coverage. I expect to have this PR done in a few days.

**Comment by coderzhaoziwei** [comment]
Thanks for your reply. I will try to config the meta builder first.

And not only the meta.

For example (with `vite-plugin-pages`):
There is a markdown file named `2022-05-01-file-name.md` in the folder `/pages/path/`. 
Then the default route name is `2022-05-01-file-name`, and the default route path is `/path/2022-05-01-file-name`.

```yaml
---
name: FileName
path: /another/route/path
---
```

If settings for name and path could be worked as above, that would be great.

**Comment by yankeeinlondon** [comment]
i'm not sure I understand the idea about the **path** as this would typically have a `1:1` relationship with the filename and path of the Markdown file right? With regard to the route's name, I can see some sense there ... I personally rarely rely on named routes but since `name` is a root level property we would need to treat it differently were we to offer the ability to modify this.

**Comment by coderzhaoziwei** [comment]
Yes, `name` or `path` would be treated differently as root props.

If frontmatter in `*.md` would be worked same as `<route>` in `*.vue`, it would be comfortable and convenient.

My English may not express clearly, thank you for your patience.

**Comment by yankeeinlondon** [comment]
this work in `v0.16.0`
