### ISSUE TITLE
Use {{variable}} in code block  variable is not defined

### ISSUE THREAD

**Issue by Soya-xy** [antfu/vite-plugin-md#74]
Reference viet-plugin-md in Nuxt3. Create an `.md` file by referring to the importing method of unocss

```html
<p>{{ name }}</p>
```

Prompt name is not defined
This seems to be processed as a VUE component and should be output as pre

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/56671014/168475103-19f87685-7a94-4aca-b142-187d9c9e1756.png">

**Comment by Soya-xy** [comment]
Minimum repetition library

https://stackblitz.com/edit/nuxt-starter-maafkj?file=package.json

**Comment by yankeeinlondon** [comment]
please do not use Nuxt in your MRL; there is no "M" in that ;)

**Comment by yankeeinlondon** [comment]
I can say that you're markdown file will 100% work if you're using the plugin correctly but I'm not going to debug how you're using it. If you think I'm wrong please create a _minimally_ reproducible example. Until then I will close.
