### ISSUE TITLE
Markdown document compilation problem

### ISSUE THREAD

**Issue by zguiyang** [antfu/vite-plugin-md#81]
# My question:

1.  Create a ``button.md``
2. Imported in route configuration:

````
 {
        path: 'button',
        name: 'component.button.md',
        component: () => import('../doc/component/button.md'),
}
````
3. run ``npm run dev``
4.  A warning message appears on the console:
````
[Vue warn]: Do not use built-in or reserved HTML elements as component id: button 
  at <Button onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <MainRouteView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <BasicLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
````

The problem is caused by rendering `` button.md`` as a ``<Button>``component while rendering markdown

# Expected behavior

No error information is displayed on the console

Can you render `` button.md`` as a ``<Button.md>``component, or render component names I can configure

# Version information

``v0.13.1``

**Comment by yankeeinlondon** [comment]
please produce a reprodicable example or else this will not get any attention.

**Comment by yankeeinlondon** [comment]
feel free to create a minamally reproducible example and re-open
