### ISSUE TITLE
Issue with latest vite version 2.9.10 

### ISSUE THREAD

**Issue by riderx** [antfu/vite-plugin-md#87]
<img width="1247" alt="Screenshot 2022-06-09 at 19 23 25" src="https://user-images.githubusercontent.com/4084527/172917771-459f5511-ded4-49b4-83ad-be273bd35093.png">
Cannot build

**Comment by prescience-data** [comment]
Same issue on latest version, fixed by rolling back to `0.13.1`.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by riderx** [comment]
I cannot reproduce on fresh repo, so the issue come from upgrading module on old version of the template, difficult to share proper reproduction in this case.

**Comment by husayt** [comment]
have the same issue
