### ISSUE TITLE
Cannot use <script lang= "ts" setup> in markdown

### ISSUE THREAD

**Issue by FuBaooo** [antfu/vite-plugin-md#91]
I noticed a file `script-hoisting.test.ts` in the test case. I try to use the same syntax in `example`, but I failed.
I tried a lot of ways. It seems that this part is all broken.

**↓↓↓↓↓↓↓↓↓↓↓You can see examples here↓↓↓↓↓↓↓↓↓↓↓**
[demo](https://stackblitz.com/edit/vitejs-vite-2754vc?file=example/src/pages/index.md)
**↑↑↑↑↑↑↑↑↑↑↑You can see examples here↑↑↑↑↑↑↑↑↑↑↑**

![image](https://user-images.githubusercontent.com/43855486/173194996-3a56eaff-9346-490a-92b0-81742f2bf5e6.png)
<img width="887" alt="image" src="https://user-images.githubusercontent.com/43855486/173195630-1314c212-a180-4528-9b4a-7a56260d6be5.png">

![image](https://user-images.githubusercontent.com/43855486/173195076-03986ca9-fc09-4b53-bd92-428963d7a9ed.png)

**Comment by yankeeinlondon** [comment]
@FuBaooo I am working a new PR and I have switched in your test file as the repo's primary test mechanism as it supports your view that this is not working as it should.

**Comment by yankeeinlondon** [comment]
note that you can get everything to work if you're secondary script blocks are just `<script>` blocks and _not_ `<script setup>` blocks, right?

**Comment by FuBaooo** [comment]
I haven't tried `<script>` yet, but I think `<script setup>` should work normally since it is in the [test case](https://raw.githubusercontent.com/antfu/vite-plugin-md/main/test/fixtures/hoisted.md).
I tried to copy the usage method in the test example, but failed.I think since it is in the test case, it should work

> note that you can get everything to work if you're secondary script blocks are just `<script>` blocks and _not_ `<script setup>` blocks, right? This is the difference which you introduced in repeating the `<script setup>` block multiple times which I'm not sure would ever have worked. Does it say it should work in the docs?

**Comment by yankeeinlondon** [comment]
The test case I had before worked fine but your test case added multiple `<script setup>` blocks which did not work. I think in general it would be a better idea for people to add `<script>` blocks in their code simply because the cardinality of `<script>` is **1:M** but that said I have updated the test to the more aggressive test you introduced and I have all tests passing there too now with a little refactoring. This code isn't released yet but will be soon.

**Comment by yankeeinlondon** [comment]
this is fixed in `v0.16.0`
